# coding: utf-8
RSpec.describe Template, type: :model do
  it 'should post opt to register template' do
    res = Template.post(OPT)
    expect(res.status).to eq(204).or eq(409)
  end

  it 'should list template' do
    res = Template.get_list
    expect(res.size).to be >=1
  end
end

OPT=<<END
<?xml version="1.0" encoding="utf-8"?>
<!--Operational template XML automatically generated by Ocean Template Designer Version 3.0.169-->
<template xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.openehr.org/v1">
  <language>
    <terminology_id>
      <value>ISO_639-1</value>
    </terminology_id>
    <code_string>ja</code_string>
  </language>
  <description>
    <original_author id="Original Author">Not Specified</original_author>
    <lifecycle_state>Initial</lifecycle_state>
    <other_details id="MetaDataSet:Sample Set ">Template metadata sample set </other_details>
    <other_details id="Acknowledgements"></other_details>
    <other_details id="Business Process Level"></other_details>
    <other_details id="Care setting"></other_details>
    <other_details id="Client group"></other_details>
    <other_details id="Clinical Record Element"></other_details>
    <other_details id="Copyright"></other_details>
    <other_details id="Issues"></other_details>
    <other_details id="Owner"></other_details>
    <other_details id="Sign off"></other_details>
    <other_details id="Speciality"></other_details>
    <other_details id="User roles"></other_details>
    <details>
      <language>
        <terminology_id>
          <value>ISO_639-1</value>
        </terminology_id>
        <code_string>ja</code_string>
      </language>
      <purpose>Not Specified</purpose>
    </details>
  </description>
  <uid>
    <value>17bed299-2c1e-42cc-afb3-6d78002dcce3</value>
  </uid>
  <template_id>
    <value>symptom_screening</value>
  </template_id>
  <concept>symptom_screening</concept>
  <definition>
    <rm_type_name>COMPOSITION</rm_type_name>
    <occurrences>
      <lower_included>true</lower_included>
      <upper_included>true</upper_included>
      <lower_unbounded>false</lower_unbounded>
      <upper_unbounded>false</upper_unbounded>
      <lower>1</lower>
      <upper>1</upper>
    </occurrences>
    <node_id>at0000</node_id>
    <attributes xsi:type="C_SINGLE_ATTRIBUTE">
      <rm_attribute_name>category</rm_attribute_name>
      <existence>
        <lower_included>true</lower_included>
        <upper_included>true</upper_included>
        <lower_unbounded>false</lower_unbounded>
        <upper_unbounded>false</upper_unbounded>
        <lower>1</lower>
        <upper>1</upper>
      </existence>
      <children xsi:type="C_COMPLEX_OBJECT">
        <rm_type_name>DV_CODED_TEXT</rm_type_name>
        <occurrences>
          <lower_included>true</lower_included>
          <upper_included>true</upper_included>
          <lower_unbounded>false</lower_unbounded>
          <upper_unbounded>false</upper_unbounded>
          <lower>1</lower>
          <upper>1</upper>
        </occurrences>
        <node_id />
        <attributes xsi:type="C_SINGLE_ATTRIBUTE">
          <rm_attribute_name>defining_code</rm_attribute_name>
          <existence>
            <lower_included>true</lower_included>
            <upper_included>true</upper_included>
            <lower_unbounded>false</lower_unbounded>
            <upper_unbounded>false</upper_unbounded>
            <lower>1</lower>
            <upper>1</upper>
          </existence>
          <children xsi:type="C_CODE_PHRASE">
            <rm_type_name>CODE_PHRASE</rm_type_name>
            <occurrences>
              <lower_included>true</lower_included>
              <upper_included>true</upper_included>
              <lower_unbounded>false</lower_unbounded>
              <upper_unbounded>false</upper_unbounded>
              <lower>1</lower>
              <upper>1</upper>
            </occurrences>
            <node_id />
            <terminology_id>
              <value>openehr</value>
            </terminology_id>
            <code_list>433</code_list>
          </children>
        </attributes>
      </children>
    </attributes>
    <attributes xsi:type="C_SINGLE_ATTRIBUTE">
      <rm_attribute_name>context</rm_attribute_name>
      <existence>
        <lower_included>true</lower_included>
        <upper_included>true</upper_included>
        <lower_unbounded>false</lower_unbounded>
        <upper_unbounded>false</upper_unbounded>
        <lower>0</lower>
        <upper>1</upper>
      </existence>
      <children xsi:type="C_COMPLEX_OBJECT">
        <rm_type_name>EVENT_CONTEXT</rm_type_name>
        <occurrences>
          <lower_included>true</lower_included>
          <upper_included>true</upper_included>
          <lower_unbounded>false</lower_unbounded>
          <upper_unbounded>false</upper_unbounded>
          <lower>1</lower>
          <upper>1</upper>
        </occurrences>
        <node_id />
        <attributes xsi:type="C_SINGLE_ATTRIBUTE">
          <rm_attribute_name>other_context</rm_attribute_name>
          <existence>
            <lower_included>true</lower_included>
            <upper_included>true</upper_included>
            <lower_unbounded>false</lower_unbounded>
            <upper_unbounded>false</upper_unbounded>
            <lower>0</lower>
            <upper>1</upper>
          </existence>
          <children xsi:type="C_COMPLEX_OBJECT">
            <rm_type_name>ITEM_TREE</rm_type_name>
            <occurrences>
              <lower_included>true</lower_included>
              <upper_included>true</upper_included>
              <lower_unbounded>false</lower_unbounded>
              <upper_unbounded>false</upper_unbounded>
              <lower>1</lower>
              <upper>1</upper>
            </occurrences>
            <node_id>at0001</node_id>
            <attributes xsi:type="C_MULTIPLE_ATTRIBUTE">
              <rm_attribute_name>items</rm_attribute_name>
              <existence>
                <lower_included>true</lower_included>
                <upper_included>true</upper_included>
                <lower_unbounded>false</lower_unbounded>
                <upper_unbounded>false</upper_unbounded>
                <lower>0</lower>
                <upper>1</upper>
              </existence>
              <children xsi:type="ARCHETYPE_SLOT">
                <rm_type_name>CLUSTER</rm_type_name>
                <occurrences>
                  <lower_included>true</lower_included>
                  <lower_unbounded>false</lower_unbounded>
                  <upper_unbounded>true</upper_unbounded>
                  <lower>0</lower>
                </occurrences>
                <node_id>at0002</node_id>
                <includes>
                  <expression xsi:type="EXPR_BINARY_OPERATOR">
                    <type>Boolean</type>
                    <operator>2007</operator>
                    <precedence_overridden>false</precedence_overridden>
                    <left_operand xsi:type="EXPR_LEAF">
                      <type>String</type>
                      <item xsi:type="xsd:string">archetype_id/value</item>
                      <reference_type>attribute</reference_type>
                    </left_operand>
                    <right_operand xsi:type="EXPR_LEAF">
                      <type>C_STRING</type>
                      <item xsi:type="C_STRING">
                        <pattern>.*</pattern>
                      </item>
                      <reference_type>constraint</reference_type>
                    </right_operand>
                  </expression>
                </includes>
              </children>
              <cardinality>
                <is_ordered>false</is_ordered>
                <is_unique>false</is_unique>
                <interval>
                  <lower_included>true</lower_included>
                  <lower_unbounded>false</lower_unbounded>
                  <upper_unbounded>true</upper_unbounded>
                  <lower>0</lower>
                </interval>
              </cardinality>
            </attributes>
          </children>
        </attributes>
      </children>
    </attributes>
    <attributes xsi:type="C_MULTIPLE_ATTRIBUTE">
      <rm_attribute_name>content</rm_attribute_name>
      <existence>
        <lower_included>true</lower_included>
        <upper_included>true</upper_included>
        <lower_unbounded>false</lower_unbounded>
        <upper_unbounded>false</upper_unbounded>
        <lower>0</lower>
        <upper>1</upper>
      </existence>
      <children xsi:type="C_ARCHETYPE_ROOT">
        <rm_type_name>OBSERVATION</rm_type_name>
        <occurrences>
          <lower_included>true</lower_included>
          <lower_unbounded>false</lower_unbounded>
          <upper_unbounded>true</upper_unbounded>
          <lower>0</lower>
        </occurrences>
        <node_id>at0000</node_id>
        <attributes xsi:type="C_SINGLE_ATTRIBUTE">
          <rm_attribute_name>data</rm_attribute_name>
          <existence>
            <lower_included>true</lower_included>
            <upper_included>true</upper_included>
            <lower_unbounded>false</lower_unbounded>
            <upper_unbounded>false</upper_unbounded>
            <lower>1</lower>
            <upper>1</upper>
          </existence>
          <children xsi:type="C_COMPLEX_OBJECT">
            <rm_type_name>HISTORY</rm_type_name>
            <occurrences>
              <lower_included>true</lower_included>
              <upper_included>true</upper_included>
              <lower_unbounded>false</lower_unbounded>
              <upper_unbounded>false</upper_unbounded>
              <lower>1</lower>
              <upper>1</upper>
            </occurrences>
            <node_id>at0001</node_id>
            <attributes xsi:type="C_MULTIPLE_ATTRIBUTE">
              <rm_attribute_name>events</rm_attribute_name>
              <existence>
                <lower_included>true</lower_included>
                <upper_included>true</upper_included>
                <lower_unbounded>false</lower_unbounded>
                <upper_unbounded>false</upper_unbounded>
                <lower>0</lower>
                <upper>1</upper>
              </existence>
              <children xsi:type="C_COMPLEX_OBJECT">
                <rm_type_name>EVENT</rm_type_name>
                <occurrences>
                  <lower_included>true</lower_included>
                  <upper_included>true</upper_included>
                  <lower_unbounded>false</lower_unbounded>
                  <upper_unbounded>false</upper_unbounded>
                  <lower>0</lower>
                  <upper>1</upper>
                </occurrences>
                <node_id>at0002</node_id>
                <attributes xsi:type="C_SINGLE_ATTRIBUTE">
                  <rm_attribute_name>data</rm_attribute_name>
                  <existence>
                    <lower_included>true</lower_included>
                    <upper_included>true</upper_included>
                    <lower_unbounded>false</lower_unbounded>
                    <upper_unbounded>false</upper_unbounded>
                    <lower>1</lower>
                    <upper>1</upper>
                  </existence>
                  <children xsi:type="C_COMPLEX_OBJECT">
                    <rm_type_name>ITEM_TREE</rm_type_name>
                    <occurrences>
                      <lower_included>true</lower_included>
                      <upper_included>true</upper_included>
                      <lower_unbounded>false</lower_unbounded>
                      <upper_unbounded>false</upper_unbounded>
                      <lower>1</lower>
                      <upper>1</upper>
                    </occurrences>
                    <node_id>at0003</node_id>
                    <attributes xsi:type="C_MULTIPLE_ATTRIBUTE">
                      <rm_attribute_name>items</rm_attribute_name>
                      <existence>
                        <lower_included>true</lower_included>
                        <upper_included>true</upper_included>
                        <lower_unbounded>false</lower_unbounded>
                        <upper_unbounded>false</upper_unbounded>
                        <lower>0</lower>
                        <upper>1</upper>
                      </existence>
                      <children xsi:type="C_COMPLEX_OBJECT">
                        <rm_type_name>ELEMENT</rm_type_name>
                        <occurrences>
                          <lower_included>true</lower_included>
                          <lower_unbounded>false</lower_unbounded>
                          <upper_unbounded>true</upper_unbounded>
                          <lower>0</lower>
                        </occurrences>
                        <node_id>at0004</node_id>
                        <attributes xsi:type="C_SINGLE_ATTRIBUTE">
                          <rm_attribute_name>value</rm_attribute_name>
                          <existence>
                            <lower_included>true</lower_included>
                            <upper_included>true</upper_included>
                            <lower_unbounded>false</lower_unbounded>
                            <upper_unbounded>false</upper_unbounded>
                            <lower>0</lower>
                            <upper>1</upper>
                          </existence>
                          <children xsi:type="C_COMPLEX_OBJECT">
                            <rm_type_name>DV_TEXT</rm_type_name>
                            <occurrences>
                              <lower_included>true</lower_included>
                              <upper_included>true</upper_included>
                              <lower_unbounded>false</lower_unbounded>
                              <upper_unbounded>false</upper_unbounded>
                              <lower>1</lower>
                              <upper>1</upper>
                            </occurrences>
                            <node_id />
                          </children>
                        </attributes>
                      </children>
                      <children xsi:type="C_ARCHETYPE_ROOT">
                        <rm_type_name>CLUSTER</rm_type_name>
                        <occurrences>
                          <lower_included>true</lower_included>
                          <lower_unbounded>false</lower_unbounded>
                          <upper_unbounded>true</upper_unbounded>
                          <lower>0</lower>
                        </occurrences>
                        <node_id>at0000</node_id>
                        <attributes xsi:type="C_MULTIPLE_ATTRIBUTE">
                          <rm_attribute_name>items</rm_attribute_name>
                          <existence>
                            <lower_included>true</lower_included>
                            <upper_included>true</upper_included>
                            <lower_unbounded>false</lower_unbounded>
                            <upper_unbounded>false</upper_unbounded>
                            <lower>1</lower>
                            <upper>1</upper>
                          </existence>
                          <children xsi:type="C_COMPLEX_OBJECT">
                            <rm_type_name>ELEMENT</rm_type_name>
                            <occurrences>
                              <lower_included>true</lower_included>
                              <upper_included>true</upper_included>
                              <lower_unbounded>false</lower_unbounded>
                              <upper_unbounded>false</upper_unbounded>
                              <lower>1</lower>
                              <upper>1</upper>
                            </occurrences>
                            <node_id>at0001</node_id>
                            <attributes xsi:type="C_SINGLE_ATTRIBUTE">
                              <rm_attribute_name>value</rm_attribute_name>
                              <existence>
                                <lower_included>true</lower_included>
                                <upper_included>true</upper_included>
                                <lower_unbounded>false</lower_unbounded>
                                <upper_unbounded>false</upper_unbounded>
                                <lower>0</lower>
                                <upper>1</upper>
                              </existence>
                              <children xsi:type="C_COMPLEX_OBJECT">
                                <rm_type_name>DV_TEXT</rm_type_name>
                                <occurrences>
                                  <lower_included>true</lower_included>
                                  <upper_included>true</upper_included>
                                  <lower_unbounded>false</lower_unbounded>
                                  <upper_unbounded>false</upper_unbounded>
                                  <lower>1</lower>
                                  <upper>1</upper>
                                </occurrences>
                                <node_id />
                              </children>
                            </attributes>
                          </children>
                          <children xsi:type="ARCHETYPE_SLOT">
                            <rm_type_name>CLUSTER</rm_type_name>
                            <occurrences>
                              <lower_included>true</lower_included>
                              <lower_unbounded>false</lower_unbounded>
                              <upper_unbounded>true</upper_unbounded>
                              <lower>0</lower>
                            </occurrences>
                            <node_id>at0147</node_id>
                            <includes>
                              <expression xsi:type="EXPR_BINARY_OPERATOR">
                                <type>Boolean</type>
                                <operator>2007</operator>
                                <precedence_overridden>false</precedence_overridden>
                                <left_operand xsi:type="EXPR_LEAF">
                                  <type>String</type>
                                  <item xsi:type="xsd:string">archetype_id/value</item>
                                  <reference_type>attribute</reference_type>
                                </left_operand>
                                <right_operand xsi:type="EXPR_LEAF">
                                  <type>C_STRING</type>
                                  <item xsi:type="C_STRING">
                                    <pattern>openEHR-EHR-CLUSTER\.anatomical_location(-[a-zA-Z0-9_]+)*\.v1|openEHR-EHR-CLUSTER\.anatomical_location_clock(-[a-zA-Z0-9_]+)*\.v0|openEHR-EHR-CLUSTER\.anatomical_location_relative(-[a-zA-Z0-9_]+)*\.v1</pattern>
                                  </item>
                                  <reference_type>constraint</reference_type>
                                </right_operand>
                              </expression>
                            </includes>
                            <excludes>
                              <expression xsi:type="EXPR_BINARY_OPERATOR">
                                <type>Boolean</type>
                                <operator>2007</operator>
                                <precedence_overridden>false</precedence_overridden>
                                <left_operand xsi:type="EXPR_LEAF">
                                  <type>String</type>
                                  <item xsi:type="xsd:string">archetype_id/value</item>
                                  <reference_type>attribute</reference_type>
                                </left_operand>
                                <right_operand xsi:type="EXPR_LEAF">
                                  <type>C_STRING</type>
                                  <item xsi:type="C_STRING">
                                    <pattern>.*</pattern>
                                  </item>
                                  <reference_type>constraint</reference_type>
                                </right_operand>
                              </expression>
                            </excludes>
                          </children>
                          <children xsi:type="ARCHETYPE_SLOT">
                            <rm_type_name>CLUSTER</rm_type_name>
                            <occurrences>
                              <lower_included>true</lower_included>
                              <lower_unbounded>false</lower_unbounded>
                              <upper_unbounded>true</upper_unbounded>
                              <lower>0</lower>
                            </occurrences>
                            <node_id>at0153</node_id>
                            <includes>
                              <expression xsi:type="EXPR_BINARY_OPERATOR">
                                <type>Boolean</type>
                                <operator>2007</operator>
                                <precedence_overridden>false</precedence_overridden>
                                <left_operand xsi:type="EXPR_LEAF">
                                  <type>String</type>
                                  <item xsi:type="xsd:string">archetype_id/value</item>
                                  <reference_type>attribute</reference_type>
                                </left_operand>
                                <right_operand xsi:type="EXPR_LEAF">
                                  <type>C_STRING</type>
                                  <item xsi:type="C_STRING">
                                    <pattern>.*</pattern>
                                  </item>
                                  <reference_type>constraint</reference_type>
                                </right_operand>
                              </expression>
                            </includes>
                          </children>
                          <children xsi:type="ARCHETYPE_SLOT">
                            <rm_type_name>CLUSTER</rm_type_name>
                            <occurrences>
                              <lower_included>true</lower_included>
                              <lower_unbounded>false</lower_unbounded>
                              <upper_unbounded>true</upper_unbounded>
                              <lower>0</lower>
                            </occurrences>
                            <node_id>at0146</node_id>
                            <includes>
                              <expression xsi:type="EXPR_BINARY_OPERATOR">
                                <type>Boolean</type>
                                <operator>2007</operator>
                                <precedence_overridden>false</precedence_overridden>
                                <left_operand xsi:type="EXPR_LEAF">
                                  <type>String</type>
                                  <item xsi:type="xsd:string">archetype_id/value</item>
                                  <reference_type>attribute</reference_type>
                                </left_operand>
                                <right_operand xsi:type="EXPR_LEAF">
                                  <type>C_STRING</type>
                                  <item xsi:type="C_STRING">
                                    <pattern>openEHR-EHR-CLUSTER\.symptom_sign(-[a-zA-Z0-9_]+)*\.v0</pattern>
                                  </item>
                                  <reference_type>constraint</reference_type>
                                </right_operand>
                              </expression>
                            </includes>
                          </children>
                          <children xsi:type="ARCHETYPE_SLOT">
                            <rm_type_name>CLUSTER</rm_type_name>
                            <occurrences>
                              <lower_included>true</lower_included>
                              <lower_unbounded>false</lower_unbounded>
                              <upper_unbounded>true</upper_unbounded>
                              <lower>0</lower>
                            </occurrences>
                            <node_id>at0063</node_id>
                            <includes>
                              <expression xsi:type="EXPR_BINARY_OPERATOR">
                                <type>Boolean</type>
                                <operator>2007</operator>
                                <precedence_overridden>false</precedence_overridden>
                                <left_operand xsi:type="EXPR_LEAF">
                                  <type>String</type>
                                  <item xsi:type="xsd:string">archetype_id/value</item>
                                  <reference_type>attribute</reference_type>
                                </left_operand>
                                <right_operand xsi:type="EXPR_LEAF">
                                  <type>C_STRING</type>
                                  <item xsi:type="C_STRING">
                                    <pattern>openEHR-EHR-CLUSTER\.symptom_sign(-[a-zA-Z0-9_]+)*\.v0</pattern>
                                  </item>
                                  <reference_type>constraint</reference_type>
                                </right_operand>
                              </expression>
                            </includes>
                          </children>
                          <cardinality>
                            <is_ordered>false</is_ordered>
                            <is_unique>false</is_unique>
                            <interval>
                              <lower_included>true</lower_included>
                              <lower_unbounded>false</lower_unbounded>
                              <upper_unbounded>true</upper_unbounded>
                              <lower>1</lower>
                            </interval>
                          </cardinality>
                        </attributes>
                        <archetype_id>
                          <value>openEHR-EHR-CLUSTER.symptom_sign.v1</value>
                        </archetype_id>
                        <term_definitions code="at0000">
                          <items id="description">Reported observation of a physical or mental disturbance in an individual.</items>
                          <items id="text">Symptom/Sign</items>
                        </term_definitions>
                        <term_definitions code="at0001">
                          <items id="comment">Symptom name should be coded with a terminology, where possible.</items>
                          <items id="description">The name of the reported symptom or sign.</items>
                          <items id="text">Symptom/Sign name</items>
                        </term_definitions>
                        <term_definitions code="at0002">
                          <items id="description">Narrative description about the reported symptom or sign.</items>
                          <items id="text">Description</items>
                        </term_definitions>
                        <term_definitions code="at0003">
                          <items id="comment">For example: pain could be described as constant or intermittent.</items>
                          <items id="description">Narrative description about the pattern of the symptom or sign during this episode.</items>
                          <items id="text">Pattern</items>
                        </term_definitions>
                        <term_definitions code="at0017">
                          <items id="description">Perceived effect of the modifying factor on the symptom or sign.</items>
                          <items id="text">Effect</items>
                        </term_definitions>
                        <term_definitions code="at0018">
                          <items id="description">Detail about how a specific factor effects the identified symptom or sign during this episode.</items>
                          <items id="text">Modifying factor</items>
                        </term_definitions>
                        <term_definitions code="at0019">
                          <items id="comment">Examples of modifying factor: lying on multiple pillows, eating or administration of a specific medication.</items>
                          <items id="description">Name of the modifying factor.</items>
                          <items id="text">Factor</items>
                        </term_definitions>
                        <term_definitions code="at0021">
                          <items id="comment">Defining values such as mild, moderate or severe in such a way that is applicable to multiple symptoms or signs plus allows multiple users to interpret and record them consistently is not easy. Some organisations extend the value set further with inclusion of additional values such as 'Trivial' and 'Very severe', and/or 'Mild-Moderate' and 'Moderate-Severe', adds to the definitional difficulty and may also worsen inter-recorder reliability issues. Use of 'Life-threatening' and 'Fatal' is also often considered as part of this value set, although from a pure point of view it may actually reflect an outcome rather than a severity. In view of the above, keeping to a well-defined but smaller list is preferred and so the mild/moderate/severe value set is offered, however the choice of other text allows for other value sets to be included at this data element in a template. Note: more specific grading of severity can be recorded using the 'Specific details' SLOT.</items>
                          <items id="description">Category representing the overall severity of the symptom or sign.</items>
                          <items id="text">Severity category</items>
                        </term_definitions>
                        <term_definitions code="at0023">
                          <items id="description">The intensity of the symptom or sign does not cause interference with normal activity.</items>
                          <items id="text">Mild</items>
                        </term_definitions>
                        <term_definitions code="at0024">
                          <items id="description">The intensity of the symptom or sign causes interference with normal activity.</items>
                          <items id="text">Moderate</items>
                        </term_definitions>
                        <term_definitions code="at0025">
                          <items id="description">The intensity of the symptom or sign causes prevents normal activity.</items>
                          <items id="text">Severe</items>
                        </term_definitions>
                        <term_definitions code="at0026">
                          <items id="comment">Symptom severity can be rated by the individual by recording a score from 0 (ie symptom not present) to 10.0 (ie symptom is as severe as the individual can imagine). This score can be represented in the user interface as a visual analogue scale. The data element has occurrences set to 0..* to allow for variations such as 'maximal severity' or 'average severity' to be included in a template.</items>
                          <items id="description">Numerical rating scale representing the overall severity of the symptom or sign.</items>
                          <items id="text">Severity rating</items>
                        </term_definitions>
                        <term_definitions code="at0028">
                          <items id="comment">If 'Date/time of onset' and 'Date/time of resolution' are used in systems, this data element may be calculated, or alternatively, be considered redundant in this scenario.</items>
                          <items id="description">The duration of this episode of the symptom or sign since onset.</items>
                          <items id="text">Duration</items>
                        </term_definitions>
                        <term_definitions code="at0031">
                          <items id="description">The number of times this symptom or sign has previously occurred.</items>
                          <items id="text">Number of previous episodes</items>
                        </term_definitions>
                        <term_definitions code="at0035">
                          <items id="comment">Record as True if the subject of care has reported the symptom as not significant. For example: if the individual has never experienced the symptom it is appropriate to record 'nil significant'; or if the individual commonly experiences the symptom, in some circumstances it may be considered appropriate to record 'nil significant' if the individual has experienced no deviation from their 'normal' baseline.</items>
                          <items id="description">The identified symptom or sign was reported as not being present to any significant degree.</items>
                          <items id="text">Nil significant</items>
                        </term_definitions>
                        <term_definitions code="at0037">
                          <items id="comment">For example: a text description of the immediate onset of the symptom, activities that worsened or relieved the symptom, whether it is improving or worsening and how it resolved over weeks.</items>
                          <items id="description">Narrative description about the course of the symptom or sign during this episode.</items>
                          <items id="text">Episode description</items>
                        </term_definitions>
                        <term_definitions code="at0056">
                          <items id="description">Narrative description of the effect of the modifying factor on the symptom or sign.</items>
                          <items id="text">Description</items>
                        </term_definitions>
                        <term_definitions code="at0057">
                          <items id="comment">For example: frequency/periodicity - per hour, day, week, month, year; and regularity. May include a comparison to this episode.</items>
                          <items id="description">Narrative description of any or all previous episodes.</items>
                          <items id="text">Description of previous episodes</items>
                        </term_definitions>
                        <term_definitions code="at0063">
                          <items id="comment">In linked clinical systems, it is possible that associated symptoms or signs are already recorded within the EHR. Systems can allow the clinician to LINK to relevant associated symptoms/signs. However in a system or message without LINKs to existing data or with a new patient, additional instances of the symptom archetype could be included here to represent associated symptoms/signs.</items>
                          <items id="description">Structured details about any associated symptoms or signs that are concurrent.</items>
                          <items id="text">Associated symptom/sign</items>
                        </term_definitions>
                        <term_definitions code="at0146">
                          <items id="comment">In linked clinical systems, it is possible that previous episodes are already recorded within the EHR. Systems can allow the clinician to LINK to relevant previous episodes. However in a system or message without LINKs to existing data or with a new patient, additional instances of the symptom archetype could be included here to represent previous episodes. It is recommended that new instances of the Symptom archetype inserted in this SLOT represent one or many previous episodes to this Symptom instance only.</items>
                          <items id="description">Structured details of the symptom or sign during a previous episode.</items>
                          <items id="text">Previous episodes</items>
                        </term_definitions>
                        <term_definitions code="at0147">
                          <items id="comment">If the anatomical location is included in the Symptom name via precoordinated codes, use of this SLOT becomes redundant. If the anatomical location is recorded using the 'Body site' data element, then use of CLUSTER archetypes in this SLOT is not allowed - record only the simple 'Body site' OR 'Structured body site', but not both.</items>
                          <items id="description">Structured body site where the symptom or sign was reported.</items>
                          <items id="text">Structured body site</items>
                        </term_definitions>
                        <term_definitions code="at0151">
                          <items id="comment">Occurrences of this data element are set to 0..* to allow multiple body sites to be separated out in a template if desired. This allows for representation of clinical scenarios where a symptom or sign needs to be recorded in multiple locations or identifying both the originating and distal site in pain radiation, but where all of the other attributes such as impact and duration are identical. If the requirements for recording the body site are determined at run-time by the application or require more complex modelling such as relative locations then use the CLUSTER.anatomical_location or CLUSTER.relative_location within the Detailed anatomical location' SLOT in this archetype. 
If the anatomical location is included in the Symptom name via precoordinated codes, this data element becomes redundant.  If the anatomical location is recorded using the 'Structured body site' SLOT, then use of this data element is not allowed - record only the simple 'Body site' OR 'Structured body site', but not both.</items>
                          <items id="description">Simple body site where the symptom or sign was reported.</items>
                          <items id="text">Body site</items>
                        </term_definitions>
                        <term_definitions code="at0152">
                          <items id="comment">While partial dates are permitted, the exact date and time of onset can be recorded, if appropriate. If this symptom or sign is experienced for the first time or is a re-occurrence, this date is used to represent the onset of this episode. If this symptom or sign is ongoing, this data element may be redundant if it has been recorded previously.</items>
                          <items id="description">The onset for this episode of the symptom or sign.</items>
                          <items id="text">Episode onset</items>
                        </term_definitions>
                        <term_definitions code="at0153">
                          <items id="comment">For example: CTCAE grading.</items>
                          <items id="description">Specific data elements that are additionally required to record as unique attributes of the identified symptom or sign.</items>
                          <items id="text">Specific details</items>
                        </term_definitions>
                        <term_definitions code="at0154">
                          <items id="description">Structured detail about the factor associated with the identified symptom or sign.</items>
                          <items id="text">Factor detail</items>
                        </term_definitions>
                        <term_definitions code="at0155">
                          <items id="comment">Assessment of impact could consider the severity, duration and frequency of the symptom as well as the type of impact including, but not limited to, functional, social and emotional impact. Occurrences of this data element are set to 0..* to allow multiple types of impact to be separated out in a template if desired. Examples for functional impact from hearing loss may include: 'Difficulty Hearing in Quiet Environment'; 'Difficulty Hearing the TV or Radio'; 'Difficulty Hearing Group Conversation'; and 'Difficulty Hearing on Phone'.</items>
                          <items id="description">Description of the impact of this symptom or sign.</items>
                          <items id="text">Impact</items>
                        </term_definitions>
                        <term_definitions code="at0156">
                          <items id="description">The factor has no impact on the symptom or sign.</items>
                          <items id="text">No effect</items>
                        </term_definitions>
                        <term_definitions code="at0158">
                          <items id="description">The factor increases the severity or impact of the symptom or sign.</items>
                          <items id="text">Worsens</items>
                        </term_definitions>
                        <term_definitions code="at0159">
                          <items id="description">The factor decreases the severity or impact of the symptom or sign, but does not fully resolve it.</items>
                          <items id="text">Relieves</items>
                        </term_definitions>
                        <term_definitions code="at0161">
                          <items id="comment">If 'Date/time of onset' and 'Duration' are used in systems, this data element may be calculated, or alternatively, considered redundant. While partial dates are permitted, the exact date and time of resolution can be recorded, if appropriate.</items>
                          <items id="description">The timing of the cessation of this episode of the symptom or sign.</items>
                          <items id="text">Resolution date/time</items>
                        </term_definitions>
                        <term_definitions code="at0163">
                          <items id="description">Additional narrative about the symptom or sign not captured in other fields.</items>
                          <items id="text">Comment</items>
                        </term_definitions>
                        <term_definitions code="at0164">
                          <items id="comment">The type of the onset can be coded with a terminology, if desired. For example: gradual; or sudden.</items>
                          <items id="description">Description of the onset of the symptom or sign.</items>
                          <items id="text">Onset type</items>
                        </term_definitions>
                        <term_definitions code="at0165">
                          <items id="comment">For example: onset of headache occurred one week prior to menstruation; or onset of headache occurred one hour after fall of bicycle.</items>
                          <items id="description">Details about specified factors that are associated with the precipitation or resolution of the symptom or sign.</items>
                          <items id="text">Precipitating/resolving factor</items>
                        </term_definitions>
                        <term_definitions code="at0167">
                          <items id="description">Identification of factors or events that trigger the onset or commencement of the symptom or sign.</items>
                          <items id="text">Precipitating factor</items>
                        </term_definitions>
                        <term_definitions code="at0168">
                          <items id="description">Identification of factors or events that trigger resolution or cessation of the symptom or sign.</items>
                          <items id="text">Resolving factor</items>
                        </term_definitions>
                        <term_definitions code="at0170">
                          <items id="comment">For example: onset of another symptom; onset of menstruation; or fall off bicycle.</items>
                          <items id="description">Name of the health event, symptom, reported sign or other factor.</items>
                          <items id="text">Factor</items>
                        </term_definitions>
                        <term_definitions code="at0171">
                          <items id="description">The interval of time between the occurrence or onset of the factor and onset/resolution of the symptom or sign.</items>
                          <items id="text">Time interval</items>
                        </term_definitions>
                        <term_definitions code="at0175">
                          <items id="description">Category of this episode for the identified symptom or sign.</items>
                          <items id="text">Episodicity</items>
                        </term_definitions>
                        <term_definitions code="at0176">
                          <items id="description">A new episode of the symptom or sign - either the first ever occurrence or a reoccurrence where the previous episode had completely resolved.</items>
                          <items id="text">New</items>
                        </term_definitions>
                        <term_definitions code="at0177">
                          <items id="description">It is not possible to determine if this occurrence of the symptom or sign is new or ongoing.</items>
                          <items id="text">Indeterminate</items>
                        </term_definitions>
                        <term_definitions code="at0178">
                          <items id="description">This symptom or sign is ongoing, effectively a single, continuous episode.</items>
                          <items id="text">Ongoing</items>
                        </term_definitions>
                        <term_definitions code="at0180">
                          <items id="comment">Occurrences of this data element are set to 0..* to allow multiple types of progression to be separated out in a template if desired - for example, severity or frequency.</items>
                          <items id="description">Description progression of the symptom or sign at the time of reporting.</items>
                          <items id="text">Progression</items>
                        </term_definitions>
                        <term_definitions code="at0181">
                          <items id="description">The severity of the symptom or sign has improved overall during this episode.</items>
                          <items id="text">Improving</items>
                        </term_definitions>
                        <term_definitions code="at0182">
                          <items id="description">The severity of the symptom or sign has not changed overall during this episode.</items>
                          <items id="text">Unchanged</items>
                        </term_definitions>
                        <term_definitions code="at0183">
                          <items id="description">The severity of the symptom or sign has worsened overall during this episode.</items>
                          <items id="text">Worsening</items>
                        </term_definitions>
                        <term_definitions code="at0184">
                          <items id="description">The severity of the symptom or sign has resolved.</items>
                          <items id="text">Resolved</items>
                        </term_definitions>
                        <term_definitions code="at0185">
                          <items id="description">Narrative description about the effect of the factor on the identified symptom or sign.</items>
                          <items id="text">Description</items>
                        </term_definitions>
                        <term_definitions code="at0186">
                          <items id="comment">Record as True if this is the first ever occurrence of this symptom or sign.</items>
                          <items id="description">Is this the first ever occurrence of this symptom or sign?</items>
                          <items id="text">First ever?</items>
                        </term_definitions>
                        <term_bindings terminology="SNOMED-CT">
                          <items code="at0000">
                            <value>
                              <terminology_id>
                                <value>SNOMED-CT</value>
                              </terminology_id>
                              <code_string>19019007</code_string>
                            </value>
                          </items>
                          <items code="at0001">
                            <value>
                              <terminology_id>
                                <value>SNOMED-CT</value>
                              </terminology_id>
                              <code_string>19019007</code_string>
                            </value>
                          </items>
                          <items code="at0002">
                            <value>
                              <terminology_id>
                                <value>SNOMED-CT</value>
                              </terminology_id>
                              <code_string>162408000</code_string>
                            </value>
                          </items>
                          <items code="at0021">
                            <value>
                              <terminology_id>
                                <value>SNOMED-CT</value>
                              </terminology_id>
                              <code_string>162465004</code_string>
                            </value>
                          </items>
                          <items code="at0023">
                            <value>
                              <terminology_id>
                                <value>SNOMED-CT</value>
                              </terminology_id>
                              <code_string>162468002</code_string>
                            </value>
                          </items>
                          <items code="at0024">
                            <value>
                              <terminology_id>
                                <value>SNOMED-CT</value>
                              </terminology_id>
                              <code_string>162469005</code_string>
                            </value>
                          </items>
                          <items code="at0025">
                            <value>
                              <terminology_id>
                                <value>SNOMED-CT</value>
                              </terminology_id>
                              <code_string>162470006</code_string>
                            </value>
                          </items>
                          <items code="at0028">
                            <value>
                              <terminology_id>
                                <value>SNOMED-CT</value>
                              </terminology_id>
                              <code_string>162442009</code_string>
                            </value>
                          </items>
                        </term_bindings>
                      </children>
                      <cardinality>
                        <is_ordered>false</is_ordered>
                        <is_unique>false</is_unique>
                        <interval>
                          <lower_included>true</lower_included>
                          <lower_unbounded>false</lower_unbounded>
                          <upper_unbounded>true</upper_unbounded>
                          <lower>1</lower>
                        </interval>
                      </cardinality>
                    </attributes>
                  </children>
                </attributes>
              </children>
              <cardinality>
                <is_ordered>false</is_ordered>
                <is_unique>false</is_unique>
                <interval>
                  <lower_included>true</lower_included>
                  <lower_unbounded>false</lower_unbounded>
                  <upper_unbounded>true</upper_unbounded>
                  <lower>1</lower>
                </interval>
              </cardinality>
            </attributes>
          </children>
        </attributes>
        <attributes xsi:type="C_SINGLE_ATTRIBUTE">
          <rm_attribute_name>protocol</rm_attribute_name>
          <existence>
            <lower_included>true</lower_included>
            <upper_included>true</upper_included>
            <lower_unbounded>false</lower_unbounded>
            <upper_unbounded>false</upper_unbounded>
            <lower>0</lower>
            <upper>1</upper>
          </existence>
          <children xsi:type="C_COMPLEX_OBJECT">
            <rm_type_name>ITEM_TREE</rm_type_name>
            <occurrences>
              <lower_included>true</lower_included>
              <upper_included>true</upper_included>
              <lower_unbounded>false</lower_unbounded>
              <upper_unbounded>false</upper_unbounded>
              <lower>1</lower>
              <upper>1</upper>
            </occurrences>
            <node_id>at0007</node_id>
            <attributes xsi:type="C_MULTIPLE_ATTRIBUTE">
              <rm_attribute_name>items</rm_attribute_name>
              <existence>
                <lower_included>true</lower_included>
                <upper_included>true</upper_included>
                <lower_unbounded>false</lower_unbounded>
                <upper_unbounded>false</upper_unbounded>
                <lower>0</lower>
                <upper>1</upper>
              </existence>
              <children xsi:type="ARCHETYPE_SLOT">
                <rm_type_name>CLUSTER</rm_type_name>
                <occurrences>
                  <lower_included>true</lower_included>
                  <lower_unbounded>false</lower_unbounded>
                  <upper_unbounded>true</upper_unbounded>
                  <lower>0</lower>
                </occurrences>
                <node_id>at0008</node_id>
                <includes>
                  <expression xsi:type="EXPR_BINARY_OPERATOR">
                    <type>Boolean</type>
                    <operator>2007</operator>
                    <precedence_overridden>false</precedence_overridden>
                    <left_operand xsi:type="EXPR_LEAF">
                      <type>String</type>
                      <item xsi:type="xsd:string">archetype_id/value</item>
                      <reference_type>attribute</reference_type>
                    </left_operand>
                    <right_operand xsi:type="EXPR_LEAF">
                      <type>C_STRING</type>
                      <item xsi:type="C_STRING">
                        <pattern>.*</pattern>
                      </item>
                      <reference_type>constraint</reference_type>
                    </right_operand>
                  </expression>
                </includes>
              </children>
              <cardinality>
                <is_ordered>false</is_ordered>
                <is_unique>false</is_unique>
                <interval>
                  <lower_included>true</lower_included>
                  <lower_unbounded>false</lower_unbounded>
                  <upper_unbounded>true</upper_unbounded>
                  <lower>0</lower>
                </interval>
              </cardinality>
            </attributes>
          </children>
        </attributes>
        <archetype_id>
          <value>openEHR-EHR-OBSERVATION.story.v1</value>
        </archetype_id>
        <term_definitions code="at0000">
          <items id="description">The subjective clinical history of the subject of care as recorded directly by the subject, or reported to a clinician by the subject or a carer.</items>
          <items id="text">Story/History</items>
        </term_definitions>
        <term_definitions code="at0001">
          <items id="description">@ internal @</items>
          <items id="text">Event Series</items>
        </term_definitions>
        <term_definitions code="at0002">
          <items id="description">Default, unspecified point in time or interval event which may be explicitly defined in a template or at run-time.</items>
          <items id="text">Any event</items>
        </term_definitions>
        <term_definitions code="at0003">
          <items id="description">@ internal @</items>
          <items id="text">Tree</items>
        </term_definitions>
        <term_definitions code="at0004">
          <items id="description">Narrative description of the story or clinical history for the subject of care.</items>
          <items id="text">Story</items>
        </term_definitions>
        <term_definitions code="at0006">
          <items id="comment">For example: a specific symptom such as nausea or pain; an event such as a fall off a bicycle; or an issue such as a desire to quit using tobacco.</items>
          <items id="description">Structured detail about the individual's story or patient's history.</items>
          <items id="text">Structured detail</items>
        </term_definitions>
        <term_definitions code="at0007">
          <items id="description">@ internal @</items>
          <items id="text">Tree</items>
        </term_definitions>
        <term_definitions code="at0008">
          <items id="comment">For example: Local information requirements or additional metadata to align with FHIR or CIMI equivalents.</items>
          <items id="description">Additional information required to capture local content or to align with other reference models/formalisms.</items>
          <items id="text">Extension</items>
        </term_definitions>
      </children>
      <children xsi:type="C_ARCHETYPE_ROOT">
        <rm_type_name>OBSERVATION</rm_type_name>
        <occurrences>
          <lower_included>true</lower_included>
          <lower_unbounded>false</lower_unbounded>
          <upper_unbounded>true</upper_unbounded>
          <lower>0</lower>
        </occurrences>
        <node_id>at0000</node_id>
        <attributes xsi:type="C_SINGLE_ATTRIBUTE">
          <rm_attribute_name>data</rm_attribute_name>
          <existence>
            <lower_included>true</lower_included>
            <upper_included>true</upper_included>
            <lower_unbounded>false</lower_unbounded>
            <upper_unbounded>false</upper_unbounded>
            <lower>1</lower>
            <upper>1</upper>
          </existence>
          <children xsi:type="C_COMPLEX_OBJECT">
            <rm_type_name>HISTORY</rm_type_name>
            <occurrences>
              <lower_included>true</lower_included>
              <upper_included>true</upper_included>
              <lower_unbounded>false</lower_unbounded>
              <upper_unbounded>false</upper_unbounded>
              <lower>1</lower>
              <upper>1</upper>
            </occurrences>
            <node_id>at0001</node_id>
            <attributes xsi:type="C_MULTIPLE_ATTRIBUTE">
              <rm_attribute_name>events</rm_attribute_name>
              <existence>
                <lower_included>true</lower_included>
                <upper_included>true</upper_included>
                <lower_unbounded>false</lower_unbounded>
                <upper_unbounded>false</upper_unbounded>
                <lower>0</lower>
                <upper>1</upper>
              </existence>
              <children xsi:type="C_COMPLEX_OBJECT">
                <rm_type_name>EVENT</rm_type_name>
                <occurrences>
                  <lower_included>true</lower_included>
                  <lower_unbounded>false</lower_unbounded>
                  <upper_unbounded>true</upper_unbounded>
                  <lower>0</lower>
                </occurrences>
                <node_id>at0002</node_id>
                <attributes xsi:type="C_SINGLE_ATTRIBUTE">
                  <rm_attribute_name>data</rm_attribute_name>
                  <existence>
                    <lower_included>true</lower_included>
                    <upper_included>true</upper_included>
                    <lower_unbounded>false</lower_unbounded>
                    <upper_unbounded>false</upper_unbounded>
                    <lower>1</lower>
                    <upper>1</upper>
                  </existence>
                  <children xsi:type="C_COMPLEX_OBJECT">
                    <rm_type_name>ITEM_LIST</rm_type_name>
                    <occurrences>
                      <lower_included>true</lower_included>
                      <upper_included>true</upper_included>
                      <lower_unbounded>false</lower_unbounded>
                      <upper_unbounded>false</upper_unbounded>
                      <lower>1</lower>
                      <upper>1</upper>
                    </occurrences>
                    <node_id>at0003</node_id>
                    <attributes xsi:type="C_MULTIPLE_ATTRIBUTE">
                      <rm_attribute_name>items</rm_attribute_name>
                      <existence>
                        <lower_included>true</lower_included>
                        <upper_included>true</upper_included>
                        <lower_unbounded>false</lower_unbounded>
                        <upper_unbounded>false</upper_unbounded>
                        <lower>0</lower>
                        <upper>1</upper>
                      </existence>
                      <children xsi:type="C_COMPLEX_OBJECT">
                        <rm_type_name>ELEMENT</rm_type_name>
                        <occurrences>
                          <lower_included>true</lower_included>
                          <upper_included>true</upper_included>
                          <lower_unbounded>false</lower_unbounded>
                          <upper_unbounded>false</upper_unbounded>
                          <lower>1</lower>
                          <upper>1</upper>
                        </occurrences>
                        <node_id>at0004</node_id>
                        <attributes xsi:type="C_SINGLE_ATTRIBUTE">
                          <rm_attribute_name>value</rm_attribute_name>
                          <existence>
                            <lower_included>true</lower_included>
                            <upper_included>true</upper_included>
                            <lower_unbounded>false</lower_unbounded>
                            <upper_unbounded>false</upper_unbounded>
                            <lower>0</lower>
                            <upper>1</upper>
                          </existence>
                          <children xsi:type="C_DV_QUANTITY">
                            <rm_type_name>DV_QUANTITY</rm_type_name>
                            <occurrences>
                              <lower_included>true</lower_included>
                              <upper_included>true</upper_included>
                              <lower_unbounded>false</lower_unbounded>
                              <upper_unbounded>false</upper_unbounded>
                              <lower>1</lower>
                              <upper>1</upper>
                            </occurrences>
                            <node_id />
                            <property>
                              <terminology_id>
                                <value>openehr</value>
                              </terminology_id>
                              <code_string>127</code_string>
                            </property>
                            <list>
                              <units>°C</units>
                            </list>
                            <list>
                              <precision>
                                <lower_included>true</lower_included>
                                <upper_included>true</upper_included>
                                <lower_unbounded>false</lower_unbounded>
                                <upper_unbounded>false</upper_unbounded>
                                <lower>1</lower>
                                <upper>1</upper>
                              </precision>
                              <units>°F</units>
                            </list>
                          </children>
                        </attributes>
                      </children>
                      <cardinality>
                        <is_ordered>false</is_ordered>
                        <is_unique>false</is_unique>
                        <interval>
                          <lower_included>true</lower_included>
                          <lower_unbounded>false</lower_unbounded>
                          <upper_unbounded>true</upper_unbounded>
                          <lower>1</lower>
                        </interval>
                      </cardinality>
                    </attributes>
                  </children>
                </attributes>
              </children>
              <cardinality>
                <is_ordered>false</is_ordered>
                <is_unique>false</is_unique>
                <interval>
                  <lower_included>true</lower_included>
                  <lower_unbounded>false</lower_unbounded>
                  <upper_unbounded>true</upper_unbounded>
                  <lower>1</lower>
                </interval>
              </cardinality>
            </attributes>
          </children>
        </attributes>
        <attributes xsi:type="C_SINGLE_ATTRIBUTE">
          <rm_attribute_name>protocol</rm_attribute_name>
          <existence>
            <lower_included>true</lower_included>
            <upper_included>true</upper_included>
            <lower_unbounded>false</lower_unbounded>
            <upper_unbounded>false</upper_unbounded>
            <lower>0</lower>
            <upper>1</upper>
          </existence>
          <children xsi:type="C_COMPLEX_OBJECT">
            <rm_type_name>ITEM_TREE</rm_type_name>
            <occurrences>
              <lower_included>true</lower_included>
              <upper_included>true</upper_included>
              <lower_unbounded>false</lower_unbounded>
              <upper_unbounded>false</upper_unbounded>
              <lower>1</lower>
              <upper>1</upper>
            </occurrences>
            <node_id>at0007</node_id>
            <attributes xsi:type="C_MULTIPLE_ATTRIBUTE">
              <rm_attribute_name>items</rm_attribute_name>
              <existence>
                <lower_included>true</lower_included>
                <upper_included>true</upper_included>
                <lower_unbounded>false</lower_unbounded>
                <upper_unbounded>false</upper_unbounded>
                <lower>0</lower>
                <upper>1</upper>
              </existence>
              <children xsi:type="ARCHETYPE_SLOT">
                <rm_type_name>CLUSTER</rm_type_name>
                <occurrences>
                  <lower_included>true</lower_included>
                  <lower_unbounded>false</lower_unbounded>
                  <upper_unbounded>true</upper_unbounded>
                  <lower>0</lower>
                </occurrences>
                <node_id>at0009</node_id>
                <includes>
                  <expression xsi:type="EXPR_BINARY_OPERATOR">
                    <type>Boolean</type>
                    <operator>2007</operator>
                    <precedence_overridden>false</precedence_overridden>
                    <left_operand xsi:type="EXPR_LEAF">
                      <type>String</type>
                      <item xsi:type="xsd:string">archetype_id/value</item>
                      <reference_type>attribute</reference_type>
                    </left_operand>
                    <right_operand xsi:type="EXPR_LEAF">
                      <type>C_STRING</type>
                      <item xsi:type="C_STRING">
                        <pattern>openEHR-EHR-CLUSTER\.device(-[a-zA-Z0-9_]+)*\.v1</pattern>
                      </item>
                      <reference_type>constraint</reference_type>
                    </right_operand>
                  </expression>
                </includes>
              </children>
              <cardinality>
                <is_ordered>false</is_ordered>
                <is_unique>false</is_unique>
                <interval>
                  <lower_included>true</lower_included>
                  <lower_unbounded>false</lower_unbounded>
                  <upper_unbounded>true</upper_unbounded>
                  <lower>0</lower>
                </interval>
              </cardinality>
            </attributes>
          </children>
        </attributes>
        <archetype_id>
          <value>openEHR-EHR-OBSERVATION.temperature.v1</value>
        </archetype_id>
        <term_definitions code="at0000">
          <items id="description">A measurement of temperature of a specified object.</items>
          <items id="text">Temperature</items>
        </term_definitions>
        <term_definitions code="at0001">
          <items id="description">@ internal @</items>
          <items id="text">Event Series</items>
        </term_definitions>
        <term_definitions code="at0002">
          <items id="description">Any event.</items>
          <items id="text">Any event</items>
        </term_definitions>
        <term_definitions code="at0003">
          <items id="description">@ internal @</items>
          <items id="text">Single</items>
        </term_definitions>
        <term_definitions code="at0004">
          <items id="description">The measured temperature of the object.</items>
          <items id="text">Temperature</items>
        </term_definitions>
        <term_definitions code="at0006">
          <items id="description">Identify the object for which the temperature is being measured.</items>
          <items id="text">Object</items>
        </term_definitions>
        <term_definitions code="at0007">
          <items id="description">@ internal @</items>
          <items id="text">List</items>
        </term_definitions>
        <term_definitions code="at0009">
          <items id="description">Details of the device used to measure the temperature.</items>
          <items id="text">Device</items>
        </term_definitions>
      </children>
      <cardinality>
        <is_ordered>false</is_ordered>
        <is_unique>false</is_unique>
        <interval>
          <lower_included>true</lower_included>
          <lower_unbounded>false</lower_unbounded>
          <upper_unbounded>true</upper_unbounded>
          <lower>0</lower>
        </interval>
      </cardinality>
    </attributes>
    <archetype_id>
      <value>openEHR-EHR-COMPOSITION.health_summary.v1</value>
    </archetype_id>
    <template_id>
      <value>symptom_screening</value>
    </template_id>
    <term_definitions code="at0000">
      <items id="description">Generic document containing a summary of health information about an individual.</items>
      <items id="text">Health summary</items>
    </term_definitions>
    <term_definitions code="at0001">
      <items id="description">@ internal @</items>
      <items id="text">Tree</items>
    </term_definitions>
    <term_definitions code="at0002">
      <items id="comment">For example: local information requirements or additional metadata to align with FHIR or CIMI equivalents.</items>
      <items id="description">Additional information required to capture local content or to align with other reference models/formalisms.</items>
      <items id="text">Extension</items>
    </term_definitions>
  </definition>
</template>
END
