default: &default
  scheme: http
  host: localhost
  port: 8080
  path_prefix: ehrbase/rest/openehr/v1/
  auth: basic
  username: ehrbase-user
  password: SuperSecretPassword
  url: http://localhost:8080/ehrbase/rest/openehr/v1/
  
development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
