default: &default
  scheme: http
  host: localhost
  port: 8080
  path: ehrbase/rest/openehr/v1
  auth: basic
  user: ehrbase-user
  password: SuperSecretPassword

development:
  <<: *default

test:
  <<: *default

production:
  host: <%= ENV['EHRBASE_HOST'] %>
  scheme: <%= ENV['EHRBASE_ACCESS_SCHEME'] %>
  host: <%= ENV['EHRBASE_LOCATION'] %>
  port: <%= ENV['EHRBASE_PORT'] %>
  path: <%= ENV['EHRBASE_ehrbase/rest/openehr/v1'] %>
  auth: <%= ENV['EHRBASE_AUTH_TYPE'] %>
  user: <%= ENV['EHRBASE_CREDENTIAL_USER'] %>
  password: "<%= ENV['EHRBASE_CREDENTIAL_SECRET_KEY'] %>"
  

  
